### PR TITLE
Login functionality (using express and bodyparser)

### PR DESCRIPTION
**Pull request by someEcoder**

### CODE REVIEW

**Comment by MiloAkerman** [comment]
The diffs are weird. Could you upload the files using Github Desktop?
image

**Review by someEcoder — COMMENTED** [review]
README.md has no changes. The update just replaces the file content with the same content it had before. Home.html just has changes to indenting. login.html adds onclick entry points. This is mainly done for server communication through http. home.js had a few issues, so I had to change somethings. For example, `localStorage.getItem("session_token")` always returns a string even when the value is null. In other words, null will be returned as 'null', and it has to be checked as such. I was able to test this with the login (1234, test). login.js is almost purely just sending data to the server. sever.js looks complicated, but it is simple. It sends JavaScript code to the browser to send you to the next page if your username and password match a case in the database. Included in this JavaScript Code is `localStorage.setItem("session_token","testing")`. Realistically, the should be username and password so the data could be checked at each entrance point. Also, I would advise against the use of checking if the value of the local storage item is null. Doing so could result in the user being able to input any random value to get past the check. I know because I did so myself.  package-lock.json are just modules: express,axios,bodyparser.

**Comment by MiloAkerman** [comment]
Yes I understand the changes but for maintenance of the GitHub repo could you please reset the fork and make all the necessary changes with GitHub Desktop so that unneccesary changes don't show up on the "Files Changed" tab?

**Comment by blake142** [comment]
hi

**Pull request merged**
